#!/usr/bin/env bash

cd /home/uday1/projects/s3-upload-angular-test
npm install
ng build --prod
scp -r -i /home/uday1/projects/pems/woe-new-4.pem ./dist/s3-upload-angular-test/* ubuntu@ec2-35-178-113-52.eu-west-2.compute.amazonaws.com:/var/www/html/
