#!/usr/bin/env bash
cd /home/ubuntu/s3-upload-angular-test
git pull origin master
ls
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash
. ~/.nvm/nvm.sh
nvm install v14.15.0
node -v
npm install -g @angular/cli
ng --version
ng build --prod