#!/usr/bin/env bash
cd /home/uday1/projects/s3-upload-angular-test
if [ -d dist ] 
then
    aws s3 cp ./dist/ --recursive s3://test-bucket/web/ --acl public-read
else
    echo “dist folder not found”
exit 1